name: updateTargetBranch

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  upToDate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed to push to PR branches
    steps:
      - name: Auto-merge base branch into PR branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} repo
          cd repo
          git checkout ${{ github.head_ref }}
          git fetch origin ${{ github.base_ref }}
          git merge origin/${{ github.base_ref }} --no-edit || echo "No changes to merge"
          git push origin HEAD