name: updateTargetBranch

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  upToDate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout the PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge base branch into PR branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git merge origin/${{ github.event.pull_request.base.ref }} --no-edit || echo "No changes"
          git push origin HEAD